### ISSUE TITLE
I have a question ?

### ISSUE THREAD

**Issue by nnhhoang** [WXY1427/Graph-learning-to-accelerate-MOIP#2]
I'm doing task assignment problem ( here is my binary integer modelling for my problem: https://docs.google.com/document/d/1bIVfe7zvKYi7iSSYFliLZKu_dilnGath/edit?usp=sharing&ouid=111468661622117320886&rtpof=true&sd=true)
I want to ask can my modelling can use your paper or do you have any paper that give idea can solve this

**Comment by nnhhoang** [comment]
i just update my IP model ( translate it to English)

**Comment by WXY1427** [comment]
I took a quick look. With your single-objective IP model, you may choose any approach in papers "Learning large neighborhood search policy for integer programming" or "Learning Large Neighborhood Search for Vehicle Routing in Airport Ground Handling". They showcase different ways to solve IP. Hope they are helpful.

**Comment by nnhhoang** [comment]
Sorry, but my problem is multi objective. I show it in my IP model :(

**Comment by WXY1427** [comment]
Then you may use the ODA in this paper "Graph Learning Assisted Multi-Objective Integer Programming" to solve your model and accelerate it with the graph learning. Or you may consider the baselines in experiments, which are able to solve your problem, with or without IP models.
